server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notificacao-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      value-type: com.postechfiap.meuhospital.dto.AvaliacaoCriadaEvent


app:
  kafka:
    topic-notificacao: avaliacao-notificacao

logging:
  level:
    root: INFO
    com.postechfiap: DEBUG
    org.springframework.mail: DEBUG
