server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: ${APPSETTING_KAFKA_BOOTSTRAP_SERVERS:fallback}
    consumer:
      group-id: notificacao-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.postechfiap.meuhospital.dto.AvaliacaoCriadaEvent
    # ESTE BLOCO ABAIXO É O QUE FALTA:
    properties:
      security.protocol: ${APPSETTING_KAFKA_SECURITY_PROTOCOL:fallback}
      sasl.mechanism: ${APPSETTING_KAFKA_SASL_MECHANISM:fallback}
      sasl.jaas.config: ${APPSETTING_KAFKA_SASL_JAAS_CONFIG:fallback}

app:
  kafka:
    topic-notificacao: avaliacao-notificacao

logging:
  level:
    root: INFO
    com.postechfiap: DEBUG
    org.springframework.mail: DEBUG
