services:

  # ------ DB CURSOS ------
  db-cursos:
    image: postgres:16-alpine
    container_name: db-cursos
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${CURSOS_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_data/cursos:/var/lib/postgresql/data
    networks:
      - hospital_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------ MS CURSOS ------
  ms-cursos:
    build:
      context: .
      dockerfile: ms-cursos/Dockerfile
    container_name: ms-cursos
    ports:
      - "8084:8084"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-cursos:5432/${CURSOS_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      db-cursos:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: on-failure
    networks:
      - hospital_network

  # ------ MS NOTIFICACAO ------
  ms-notificacao:
    build:
      context: .
      dockerfile: ms-notificacao/Dockerfile
    container_name: ms-notificacao
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DB}?authSource=admin
    depends_on:
      kafka:
        condition: service_healthy
      db-notificacao-mongo:
        condition: service_started
    restart: on-failure
    networks:
      - hospital_network

  # ------ MONGO ------
  db-notificacao-mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
      - ./data/mongo_data/notificacao:/data/db
    networks:
      - hospital_network
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
    depends_on:
      - db-notificacao-mongo
    networks:
      - hospital_network

  # ------ ZOOKEEPER ------
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    networks:
      - hospital_network

  # ------ KAFKA ------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093


networks:
  hospital_network:
    driver: bridge