server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://db-cursos:5432/${CURSOS_DB_NAME:curso_db}
    #url: jdbc:postgresql://localhost:5432/curso_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  kafka:
#    #topic-medico-update: medico-events
#    topic-notificacao: notificacao-events

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic-notificacao: avaliacao-notificacao

  jwt:
    secret: ${APP_JWT_SECRET:my-secret-key-1234567890123456789012345678901234567890123456789012345678901234}
    expiration: ${APP_JWT_EXPIRATION_MS:86400000}


  auth-service-url: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}/usuarios
  internal-secret: ${INTERNAL_SECRET}

