server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://db-cursos:5432/${CURSOS_DB_NAME}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  kafka:
#    #topic-medico-update: medico-events
#    topic-notificacao: notificacao-events

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic-notificacao: avaliacao-notificacao

