<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.postechfiap.faculdade</groupId>
		<artifactId>faculdade-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<packaging>jar</packaging>
	<artifactId>ms-notificacao</artifactId>
	<name>Microserviço de Notificação</name>
	<description>Consumidor de eventos de agendamento e envio de lembretes.</description>
	<url/>

	<dependencies>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<!-- Spring Mail para envio via SMTP (MailHog) -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>

		<!-- Spring Data MongoDB -->
<!--		<dependency>-->
<!--			<groupId>org.springframework.boot</groupId>-->
<!--			<artifactId>spring-boot-starter-data-mongodb</artifactId>-->
<!--		</dependency>-->

		<!-- Jackson DATABIND -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>

		<!-- Módulo de Contratos -->
		<dependency>
			<groupId>com.postechfiap.faculdade</groupId>
			<artifactId>ms-contracts</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

		<!--Azure-->
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-communication-email</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		    <plugin>
		        <groupId>com.microsoft.azure</groupId>
		        <artifactId>azure-webapp-maven-plugin</artifactId>
		        <version>2.13.0</version>
		        <configuration>
		            <schemaVersion>v2</schemaVersion>
		            <resourceGroup>ms-notificacao-1767879021233-rg</resourceGroup>
		            <appName>ms-notificacao-1767879021233</appName>
		            <pricingTier>P1v2</pricingTier>
		            <region>centralus</region>
		            <runtime>
		                <os>Linux</os>
		                <javaVersion>Java 17</javaVersion>
		                <webContainer>Java SE</webContainer>
		            </runtime>
		            <deployment>
		                <resources>
		                    <resource>
		                        <directory>${project.basedir}/target</directory>
		                        <includes>
		                            <include>*.jar</include>
		                        </includes>
		                    </resource>
		                </resources>
		            </deployment>
		        </configuration>
		    </plugin>
		</plugins>
	</build>

</project>